### ISSUE TITLE
Activate GitHub Pages

### ISSUE THREAD

**Issue by ratnanil** [JereHu/cma_project#1]
It seems you haven't activated Github Pages yet. Can you do this?

- Go to Settings → Pages →Choose your branch (Main or Master) → Select Folder "Root"
- Once your page is ready, the url to your website is: pablo-oelbi.github.io/pted_semester-project

**Comment by JereHu** [comment]
Hey Nils
That's because I have not rendered an html yet.
I added it (https://jerehu.github.io/cma_project/index.html)
